

export const MODAL_OPEN = "MODAL_OPEN";

export const REQUERIMENT_SELECTED = "REQUERIMENT_SELECTED";

export const REQUERIMENT_FETCH_REQUESTED = "REQUERIMENT_FETCH_REQUESTED";
export const REQUERIMENT_FETCH_SUCCEEDED = "REQUERIMENT_FETCH_SUCCEEDED";
export const REQUERIMENT_FETCH_FAILED = "REQUERIMENT_FETCH_FAILED";

export const REQUERIMENT_ADD_REQUESTED = "REQUERIMENT_ADD_REQUESTED";
export const REQUERIMENT_ADD_SUCCEEDED = "REQUERIMENT_ADD_SUCCEEDED";
export const REQUERIMENT_ADD_FAILED = "REQUERIMENT_ADD_FAILED";

export const REQUERIMENT_UPDATE_REQUESTED = "REQUERIMENT_UPDATE_REQUESTED";
export const REQUERIMENT_UPDATE_SUCCEEDED = "REQUERIMENT_UPDATE_SUCCEEDED";
export const REQUERIMENT_UPDATE_FAILED = "REQUERIMENT_UPDATE_FAILED";

export const REQUERIMENT_DELETE_REQUESTED = "REQUERIMENT_DELETE_REQUESTED";
export const REQUERIMENT_DELETE_SUCCEEDED = "REQUERIMENT_DELETE_SUCCEEDED";
export const REQUERIMENT_DELETE_FAILED = "REQUERIMENT_DELETE_FAILED";