export const MODAL_OPEN = "MODAL_OPEN";

export const REQUERIMENT_SELECTED = "REQUERIMENT_SELECTED";

export const REQUERIMENT_FETCH_REQUESTED = "REQUERIMENT_FETCH_REQUESTED";
export const REQUERIMENT_FETCH_SUCCEEDED = "REQUERIMENT_FETCH_SUCCEEDED";
export const REQUERIMENT_FETCH_FAILED = "REQUERIMENT_FETCH_FAILED";

export const REQUERIMENT_ADD_REQUESTED = "REQUERIMENT_ADD_REQUESTED";
export const REQUERIMENT_ADD_SUCCEEDED = "REQUERIMENT_ADD_SUCCEEDED";
export const REQUERIMENT_ADD_FAILED = "REQUERIMENT_ADD_FAILED";

export const REQUERIMENT_UPDATE_REQUESTED = "REQUERIMENT_UPDATE_REQUESTED";
export const REQUERIMENT_UPDATE_SUCCEEDED = "REQUERIMENT_UPDATE_SUCCEEDED";
export const REQUERIMENT_UPDATE_FAILED = "REQUERIMENT_UPDATE_FAILED";

export const REQUERIMENT_DELETE_REQUESTED = "REQUERIMENT_DELETE_REQUESTED";
export const REQUERIMENT_DELETE_SUCCEEDED = "REQUERIMENT_DELETE_SUCCEEDED";
export const REQUERIMENT_DELETE_FAILED = "REQUERIMENT_DELETE_FAILED";

export const USERS_SELECTED = "USERS_SELECTED";

export const USERS_FETCH_REQUESTED = "USERS_FETCH_REQUESTED";
export const USERS_FETCH_SUCCEEDED = "USERS_FETCH_SUCCEEDED";
export const USERS_FETCH_FAILED = "USERS_FETCH_FAILED";

export const USERS_ADD_REQUESTED = "USERS_ADD_REQUESTED";
export const USERS_ADD_SUCCEEDED = "USERS_ADD_SUCCEEDED";
export const USERS_ADD_FAILED = "USERS_ADD_FAILED";

export const USERS_UPDATE_REQUESTED = "USERS_UPDATE_REQUESTED";
export const USERS_UPDATE_SUCCEEDED = "USERS_UPDATE_SUCCEEDED";
export const USERS_UPDATE_FAILED = "USERS_UPDATE_FAILED";

export const USERS_DELETE_REQUESTED = "USERS_DELETE_REQUESTED";
export const USERS_DELETE_SUCCEEDED = "USERS_DELETE_SUCCEEDED";
export const USERS_DELETE_FAILED = "USERS_DELETE_FAILED";
